"""empty message

Revision ID: 2fa3add295a1
Revises: 800ac2abac31
Create Date: 2024-12-04 00:43:01.395905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa3add295a1'
down_revision = '800ac2abac31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket_products', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
