"""empty message

Revision ID: 800ac2abac31
Revises: 9d351b4ad325
Create Date: 2024-11-27 10:52:36.323926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800ac2abac31'
down_revision = '9d351b4ad325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_products',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('basket_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_products')
    # ### end Alembic commands ###
